sonar.projectKey=opa-uiVeri5-wdi-Test
sonar.projectName=OPA-UiVeri5-wdi-Test
sonar.projectVersion=1.0

# Path to the JS files
sonar.sources=webapp
sonar.javascript.file.suffixes=.js,.xml

# Path to the Test reports
sonar.tests=webapp/test
sonar.junit.reportPaths=target/report
sonar.javascript.lcov.reportPaths=coverage/lcov.info